<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC08K0d6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC08K0d6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC08K0d6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC08K0d6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC08K0d6\App_KernelDevDebugContainer([
    'container.build_hash' => 'C08K0d6',
    'container.build_id' => 'fe4d28e6',
    'container.build_time' => 1603069010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC08K0d6');
